# Generated by Django 3.0.8 on 2020-08-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activityPeriods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=60)),
                ('end_time', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('real_name', models.CharField(max_length=60)),
                ('timezone', models.CharField(max_length=60)),
                ('activity_periods', models.ManyToManyField(to='assign.activityPeriods')),
            ],
        ),
    ]
